name: End-to-End Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Ensure correct Node.js version
        
      - name: Install Dependencies
        run: npm ci  # Faster & ensures clean install
      
      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          install: false  # Since we already installed dependencies manually
